### ISSUE TITLE
example.js problem

### ISSUE THREAD

**Issue by DanielDees** [DanielDees/Bimini-Product-Part-ID-Decoder#8]
How do i get the file into the parse function? I put down my attempt with file = "parts.csv" but it doesn't work. How do I do this?

**Comment by kevindees** [comment]
you might need to be ing an http server...

check your php version in the terminal

```
php -v
```

if it is greater than 5.3 you should be able to use the built in server.

From you project folder in the terminal

```
cd ~/your/project/folder/location
php -S localhost:9999
```

then load that address in the browser.

then you can include it from the url using a relative path like you are trying to.

**Comment by kevindees** [comment]
http://php.net/manual/en/features.commandline.webserver.php

**Comment by kevindees** [comment]
you might need to use it as a remote file http://papaparse.com/docs#remote-files

```js
Papa.parse(url, {
	download: true,
	// rest of config ...
})
```
- `url` is the path or URL to the file to download.
- The second argument is a config object where download: true is set.
- Doesn't return anything. Results are provided asynchronously to a callback function.
